name_or_path: microsoft/Phi-3-medium-4k-instruct

model:
  peft: false
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}
    device_map: cuda
    torch_dtype: auto
    trust_remote_code: true

  generate:
    do_sample: true
    temperature: 0.99
    top_p: 0.95
    max_new_tokens: 1000

tokenizer:
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}

pipeline:
  init:
    task:
      text-generation

  call:
    max_new_tokens: 1000
    temperature: 0.0
    do_sample: false