prompt:
  system:
    content: あなたは誠実で優秀な日本人のアシスタントです。特に指示が無い場合は、常に日本語で回答してください。
name_or_path: elyza/Llama-3-ELYZA-JP-8B

model:
  peft: false
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}
    device_map: auto
    torch_dtype: auto

  eval: true

  generate:
    do_sample: true
    temperature: 0.6
    top_p: 0.9
    max_new_tokens: 1000

tokenizer:
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}

  apply_chat_template: 
    add_generation_prompt: true
    tokenize: false

  encode:
    add_special_tokens: false
    return_tensors: pt

  decode:
    skip_special_tokens: true