name_or_path: google/gemma-2-27b-it
max_new_tokens: 1000

model:
  peft: false
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}
    device_map: auto
    torch_dtype: torch.bfloat16

  generate:
    max_new_tokens: ${max_new_tokens}

tokenizer:
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}

  apply_chat_template: 
    add_generation_prompt: true
    tokenize: false
    return_tensors: pt

  encode:
    add_special_tokens: false
    return_tensors: pt

  decode:
    skip_special_tokens: true