prompt: "以下はタスクを説明する指示で、文脈を説明した入力とペアになっています。要求を適切に補完するよう応答を書いてください。\n\n### 指示:\n{user_content}\n\n### 応答:\n"
name_or_path: pfnet/plamo-13b-instruct
max_new_tokens: 1000

model:
  peft: false
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}
    device_map: auto
    torch_dtype: torch.bfloat16
    trust_remote_code: true

  generate:
    do_sample: true
    eos_token_id: 2
    pad_token_id: 3
    temperature: 1.0
    top_p: 0.95
    top_k: 50
    max_new_tokens: ${max_new_tokens}

tokenizer:
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}
    trust_remote_code: true

  call:
    return_tensors: pt

  decode:
    skip_special_tokens: true
    clean_up_tokenization_spaces: true