prompt:
  system:
    content: あなたは誠実で優秀な日本人のアシスタントです。
name_or_path: tokyotech-llm/Llama-3-Swallow-70B-Instruct-v0.1
max_new_tokens: 1000

vllm:
  init:
    model: ${name_or_path}
    tensor_parallel_size: 4
    max_model_len: 4096

  generate: {}

sample_params:
  temperature: 0.6
  top_p: 0.9
  stop: "<|eot_id|>"
  max_tokens: ${max_new_tokens}

tokenizer:
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}

  apply_chat_template: 
    add_generation_prompt: true
    tokenize: false