prompt: "以下は、タスクを説明する指示です。要求を適切に満たす応答を書きなさい。\n\n### 指示:\n{user_content}\n\n### 応答:"
name_or_path: matsuo-lab/weblab-10b-instruction-sft
max_new_tokens: 1000

model:
  peft: false
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}
    device_map: auto
    torch_dtype: torch.float16

  generate:
    do_sample: true
    temperature: 0.7
    top_p: 0.95
    max_new_tokens: ${max_new_tokens}

tokenizer:
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}

  encode:
    return_tensors: pt
    add_special_tokens: false

  decode:
    skip_special_tokens: true