prompt: "# system\n誠実で紳士的で優秀なAIアシスタントとして、簡潔でわかりやすく役に立つ回答を自信をもって答えなさい。\n\n# question\n{user_content}\n\n# answer"
name_or_path: abeja/Mixtral-8x7B-Instruct-v0.1-japanese

model:
  peft: false
  eval: true
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}
    device_map: auto
    torch_dtype: torch.float16
    use_cache: true

  generate:
    pad_token_id: self.tokenizer.pad_token_id
    eos_token_id: self.tokenizer.eos_token_id
    max_new_tokens: 1000

tokenizer:
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}

  encode:
    return_tensors: pt

  decode:
    skip_special_tokens: true