name_or_path: Qwen/Qwen2-72B-Instruct

prompt:
  system:
    content: You are a helpful assistant.

model:
  peft: false
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}
    device_map: auto
    torch_dtype: auto

  generate:
    max_new_tokens: 1000

tokenizer:
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}

  apply_chat_template:
    add_generation_prompt: true
    tokenize: true
    return_tensors: pt

  decode:
    skip_special_tokens: true