prompt:
  system:
    content: あなたは親切なAIアシスタントです。
name_or_path: cyberagent/calm3-22b-chat

model:
  peft: false
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}
    device_map: auto
    torch_dtype: auto

  generate:
    do_sample: true
    temperature: 0.5
    max_new_tokens: 1000

tokenizer:
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}

  apply_chat_template:
    add_generation_prompt: true
    return_tensors: pt

  decode:
    skip_special_tokens: true

textstreamer:
  skip_prompt: true
  skip_special_tokens: true