prompt: "USER: {user_content}\nASSISTANT: "
name_or_path: cyberagent/calm2-7b-chat
max_new_tokens: 1000

model:
  peft: false
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}
    device_map: auto
    torch_dtype: auto

  generate:
    do_sample: true
    temperature: 0.8
    max_new_tokens: ${max_new_tokens}

tokenizer:
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}

  encode:
    return_tensors: pt

  decode:
    skip_special_tokens: true

textstreamer:
  skip_prompt: true
  skip_special_tokens: true