name_or_path: mistralai/Mistral-7B-Instruct-v0.3
max_new_tokens: 1000

pipeline:
  init:
    task: text-generation
    model: ${name_or_path}
    device_map: auto
  call:
    max_new_tokens: ${max_new_tokens}