name_or_path: mistralai/Mixtral-8x22B-Instruct-v0.1

model:
  peft: false
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}

  generate:
    max_new_tokens: 1000

tokenizer:
  from_pretrained:
    pretrained_model_name_or_path: ${name_or_path}

  apply_chat_template: 
    add_generation_prompt: true
    tokenize: true
    return_tensors: pt

  decode:
    skip_special_tokens: true